name: WakaTime All-Time

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update README
        uses: athul/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          RANGE: all_time
          TOP_LANGUAGES: true
          MAX_LANGUAGES: 10
          SYMBOL_VERSION: 2
